org: thathardwareguy
app: lambda-data-filter
service: lambda-data-filter

provider:
  name: aws 
  runtime: nodejs14.x
  stage: ${opt:stage,'us-east-2'}
  
custom:
  esbuild:
    bundle: true
    minify: false

plugins:
  - serverless-esbuild
    
package:
  individually: true


functions:
  awsIotPostgresIntegration:
    handler: dist/index.handler
    events:
      - iot:
          sql: "SELECT * FROM 'metrics/gendata'"
          name: "IotPostgresRule"
          description: "Forwards IoT data to Postgres database via AWS Lambda"
          sqlVersion: "2016-03-23"
   