name: datafilterbuild

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install serverless
        run: npm install -g serverless@2.62.0

      - name: Install npm
        run: npm install

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: serverless deploy --verbose